print("Hello world")
print("aur kesa hai bsdk")
print("kaam kar rha hai na lowde")
print("email mili kya tujhe lowde")
print("EMAIL")
print("cloud se ho rha bsdk")
print("lowd")
print("connect hogya na chutiye!!!! Agent se")
print("check kar pipeline chali kya apne aap")
print("maje le rha hai toh bsdk tu, pipeline ko bar bar chla kar.")
